### ISSUE TITLE
触摸崩溃

### ISSUE THREAD

**Issue by liupengandroid** [23mf/react-native-translucent-modal#24]
Android ，  触摸Modal就崩溃
RnVersion    0.65.1
 java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent(com.facebook.react.uimanager.events.Event)' on a null object reference
        at com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(JSTouchDispatcher.java:86)
        at com.facebook.react.views.modal.ReactModalHostView$DialogRootViewGroup.onInterceptTouchEvent(ReactModalHostView.java:521)

**Comment by AndreyPatseiko** [comment]
The same problem. 
In RN 0.65.1.

Crash report from FB:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void 
       com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent(com.facebook.react.uimanager.events.Event)' on a null object reference
       at com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(JSTouchDispatcher.java:86)
       at com.facebook.react.views.modal.ReactModalHostView$DialogRootViewGroup.onInterceptTouchEvent(ReactModalHostView.java:521)


I switched to default RN modal. It support TabBar settings now - https://reactnative.dev/docs/modal#statusbartranslucent-android.

**Comment by congshengwu** [comment]
@AndreyPatseiko 
You are right, the default RN modal has supported statusBarTranslucent. 
The issue I met in this library is the onPress event cannot be triggered on the modal on RN 0.66.1.
And I switched to default RN modal, it works well.
